Repository RedHatInsights/approval-ui, pull requests merged in 2019-04, with the labels that each got.

#11 Fixed tabs navigation.
  config/spandx.config.js
  package-lock.json
  package.json
  src/App.js
  src/SmartComponents/AppTabs/AppTabs.js
Labels: bug

#12 Fixed bundle size.
  package-lock.json
  package.json
  src/SmartComponents/Request/add-request-modal.js
  src/SmartComponents/Workflow/add-workflow-modal.js
  src/SmartComponents/Workflow/remove-workflow-modal.js
Labels: bug

#15 Fixed prod/beta build.
  package.json
  src/entry-dev.js
Labels: bug

#17 Approval Request - PF4 table and pagination
  config/setupTests.js
  package.json
  src/App.scss
  src/forms/request-comment-form.schema.js
  src/helpers/request/request-helper.js
  src/helpers/shared/helpers.js
  src/redux/actions/request-actions.js
  src/redux/reducers/request-reducer.js
  src/smart-components/request/action-modal.js
  src/smart-components/request/add-request-modal.js
  src/smart-components/request/expandable-content.js
  src/smart-components/request/request-list.js
  src/smart-components/request/request-table-helpers.js
  src/smart-components/request/request.js
  src/smart-components/request/requests.js
  src/smart-components/workflow/add-workflow-modal.js
  src/test/smart-components/request/__snapshots__/requests.test.js.snap
  src/test/smart-components/request/requests.test.js
  src/utilities/store.js
Labels: enhancement

#21 Unify table and toolbar as one component (workflows, requests)
  src/presentational-components/shared/table-toolbar-view.js
  src/smart-components/request/requests.js
  src/smart-components/workflow/workflows.js
Labels: Pending

#20 Fix approval basename
  config/base.webpack.config.js
  config/spandx.config.js
  package.json
  src/entry-dev.js
  src/entry.js
Labels: bug

#16 Add NODE_OPTIONS to avoid fatal error during build.
  .travis.yml
Labels: bug

#22 Request Detail Page - Request Info Bar and Stage List
  src/App.scss
  src/Routes.js
  src/helpers/request/request-helper.js
  src/helpers/shared/user-login.js
  src/presentational-components/shared/loader-placeholders.js
  src/redux/action-types.js
  src/redux/actions/request-actions.js
  src/redux/reducers/request-reducer.js
  src/smart-components/request/action-modal.js
  src/smart-components/request/request-detail/request-detail.js
  src/smart-components/request/request-detail/request-info-bar.js
  src/smart-components/request/request-detail/request-stage-transcript.js
  src/smart-components/request/request-detail/stage-list.js
  src/smart-components/request/request-detail/stage.js
  src/smart-components/request/request-table-helpers.js
  src/smart-components/request/requests.js
  src/test/redux/actions/request-actions.test.js
  src/test/redux/reducers/request-reducer.test.js
Labels: enhancement

#25 List the action transcripts for each Request stage ( Request Detail Page)
  src/smart-components/request/request-detail/action.js
  src/smart-components/request/request-detail/stage.js
Labels: Pending, enhancement

#28 Fix double kebabs in Workflows
  src/smart-components/workflow/workflows.js
Labels: bug
