Repository RedHatInsights/approval-ui, pull requests merged in 2020-07, with the labels that each got.

#308 Update pf4 versions
  package-lock.json
  package.json
  src/forms/add-workflow.schema.js
  src/presentational-components/shared/loader-placeholders.js
  src/presentational-components/shared/table-toolbar-view.js
  src/smart-components/app-tabs/app-tabs.js
  src/smart-components/error-pages/common-api-error.js
  src/smart-components/request/action-modal.js
  src/smart-components/request/request-detail/request-detail.js
  src/smart-components/request/request-detail/request-info-bar.js
  src/smart-components/request/request-detail/request.js
  src/smart-components/workflow/add-groups/summary-content.js
  src/smart-components/workflow/remove-workflow-modal.js
  src/test/presentional-components/shared/__snapshots__/breadcrumbs.test.js.snap
  src/test/presentional-components/table-toolbar-view.test.js
  src/test/smart-components/request/request-detail/__snapshots__/request.test.js.snap
  src/test/smart-components/workflow/add-groups/__snapshots__/summary-content.test.js.snap
  src/test/smart-components/workflow/workflows.test.js
Labels: dependencies

#311 Align mobile view dropdown menu to right.
  src/presentational-components/shared/table-toolbar-view.js
Labels: bug

#317 Add variant property to modals
  src/smart-components/workflow/edit-workflow-groups-modal.js
  src/smart-components/workflow/edit-workflow-info-modal.js
  src/smart-components/workflow/remove-workflow-modal.js
Labels: bug

#321 Add dependencies message to remove workflow modal
  src/messages/workflows.messages.js
  src/smart-components/workflow/remove-workflow-modal.js
  src/test/smart-components/workflow/remove-workflow-modal.test.js
  src/utilities/constants.js
Labels: enhancement

#338 Fix wrong intl value name.
  src/smart-components/request/action-modal.js
Labels: bug
