Repository RedHatInsights/approval-ui, pull requests merged in 2020-02, with the labels that each got.

#142 Updated dates and snapshots for the request test.
  src/test/smart-components/request/request-detail/__snapshots__/request.test.js.snap
  src/test/smart-components/request/request-detail/request.test.js
Labels: test

#145 Request transcript - Use group names for child requests
  src/smart-components/request/request-detail/request.js
  src/test/smart-components/request/request-detail/__snapshots__/request.test.js.snap
  src/test/smart-components/request/request-detail/request-list.test.js
Labels: Pending, enhancement

#143 Rename 'workflows' to 'approval processes'
  src/forms/workflow-form.schema.js
  src/redux/actions/workflow-actions.js
  src/smart-components/request/requests.js
  src/smart-components/workflow/add-stages/add-stages-wizard.js
  src/smart-components/workflow/add-stages/stage-information.js
  src/smart-components/workflow/add-stages/summary-content.js
  src/smart-components/workflow/edit-workflow-info-modal.js
  src/smart-components/workflow/edit-workflow-stages-modal.js
  src/smart-components/workflow/remove-workflow-modal.js
  src/smart-components/workflow/workflows.js
  src/test/helpers/shared/user-login.test.js
  src/test/redux/actions/workflow-actions.test.js
  src/test/redux/reducers/workflow-reducer.test.js
  src/test/smart-components/workflow/add-stages/__snapshots__/stage-information.test.js.snap
  src/test/smart-components/workflow/add-stages/__snapshots__/summary-content.test.js.snap
  src/test/smart-components/workflow/add-stages/add-stages-wizard.test.js
  src/test/smart-components/workflow/add-stages/edit-workflow-info-modal.test.js
  src/test/smart-components/workflow/remove-workflow-modal.test.js
  src/test/smart-components/workflow/workflow-table-helpers.test.js
  src/test/smart-components/workflow/workflows.test.js
Labels: enhancement

#151 Apply size optimizations to approval UI.
  .babelrc
  babel.config.js
  config/base.webpack.config.js
  config/prod.webpack.config.js
  package-lock.json
  package.json
  src/App.js
  src/Routes.js
  src/helpers/shared/helpers.js
  src/presentational-components/shared/loader-placeholders.js
  src/presentational-components/shared/table-toolbar-view.js
  src/smart-components/request/expandable-content.js
  src/smart-components/request/request-detail/request-detail.js
  src/smart-components/request/request-detail/request-list.js
  src/smart-components/workflow/expandable-content.js
  src/test/presentional-components/shared/__snapshots__/filter-toolbar-item.test.js.snap
  src/test/smart-components/request/action-modal.test.js
  src/test/smart-components/request/expandable-content.test.js
  src/test/smart-components/request/request-detail/__snapshots__/request.test.js.snap
  src/test/smart-components/workflow/add-stages/__snapshots__/stage-information.test.js.snap
  src/test/smart-components/workflow/expandable-content.test.js
  src/test/smart-components/workflow/workflows.test.js
Labels: enhancement

#163 Remove live update schedule from dependabot.
  .dependabot/config.yml
Labels: dependencies

#158 Empty pages for the approval processes and requests lists
  src/presentational-components/shared/table-empty-state.js
  src/presentational-components/shared/table-toolbar-view.js
  src/smart-components/request/requests.js
  src/smart-components/workflow/workflows.js
  src/test/presentional-components/table-toolbar-view.test.js
Labels: enhancement

#175 Updated fetch data and title/description for edit info/edit sequence modals
  src/App.js
  src/Routes.js
  src/helpers/request/request-helper.js
  src/helpers/shared/helpers.js
  src/helpers/shared/user-login.js
  src/helpers/workflow/workflow-helper.js
  src/presentational-components/shared/table-toolbar-view.js
  src/redux/action-types.js
  src/redux/actions/request-actions.js
  src/redux/actions/workflow-actions.js
  src/redux/reducers/roles-reducer.js
  src/smart-components/request/requests.js
  src/smart-components/workflow/add-stages/add-stages-wizard.js
  src/smart-components/workflow/edit-workflow-info-modal.js
  src/smart-components/workflow/edit-workflow-stages-modal.js
  src/smart-components/workflow/workflow-table-helpers.js
  src/test/presentional-components/table-toolbar-view.test.js
  src/test/redux/reducers/roles-reducer.test.js
  src/test/smart-components/request/requests.test.js
  src/test/smart-components/workflow/workflow-table-helpers.test.js
  src/test/utilities/store.test.js
  src/utilities/store.js
Labels: Pending
